# elasticsearch地址
#elasticsearch-burst_case:
#  url: 127.0.0.1:9200
#  user: 1111
#  secret: 12345

# redis配置  用于防重放，需要配置
redispool-user:
  host: 127.0.0.1
  port: 6379
  password: "12345"

# redis配置
redispool-game:
  host: 127.0.0.1
  port: 6379
  password: "12345"

# redis配置
redispool-gamessd:
  host: 127.0.0.1
  port: 6379
  password: "12345"

# redis配置
redispool-archive:
  host: 127.0.0.1
  port: 6379
  password: "12345"

server:
  env: test
